version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: xoro-api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - xoro-network
    volumes:
      - ./public:/app/public
      - ./storage:/app/storage

networks:
  xoro-network:
    driver: bridge
