version: '3.8'
services:
  postgres:
    image: postgres:17.5
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8.0
    restart: always
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "", "--aclfile", "/data/redis.acl"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis.acl:/data/redis.acl
      - redisdata:/data
    environment:
      REDIS_USER: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  app:
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    volumes:
    - ./public:/usr/src/app/public   # Host bind for static assets
    - storage:/usr/src/app/storage   # Named volume for user uploads

  prisma-studio:
    build: .
    entrypoint: ["npx", "prisma", "studio", "--port", "5555"]
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5555:5555"
    volumes:
      - .:/usr/src/app

volumes:
  pgdata:
  redisdata:
  storage: